export const ERROR_CODES = {
  REQUIRED_FIELD: "REQUIRED_FIELD",
  INVALID_EMAIL: "INVALID_EMAIL",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_WEAK: "PASSWORD_WEAK",
  INVALID_FIELD: "INVALID_FIELD",
} as const;
